<?php defined('SYSPATH') OR die('No direct access allowed.');
include_once("BaseController.php");
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
abstract class BaseController_Controller extends Template_Controller
{
	// Disable this controller when Kohana is set to production mode.
	const ALLOW_PRODUCTION = FALSE;

	// Set the name of the template to use
	public $template = 'kohana/template';

	public function __construct()
	{
		// load database library into $this->db (can be omitted if not required)
		parent::__construct();
		
		$this->data['common'] = arr::to_object(Kohana::lang('common'));
		$this->site_name = Kohana::config('core.site_name');
		$this->template->breadcrumb   = html::breadcrumb();
		
		$this->newsevent = new Newsevent_Model;
		$this->data['nevents']  = $this->newsevent->get_news_event();
	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the index page, you need to use: home/index/'.substr(Router::$current_uri, 8);
	}

	protected function _loadCommonTemplate()
	{
		$dynamicMiddleContent 	  = !empty($this->view_content) ? $this->view_content : 'sources/site_middle_content';
		$dynamicLeftMiddleContent = !empty($this->view_content2) ? $this->view_content2 : 'sources/site_middle_left_menu';
		$tempContent = array(
			'SITE_TOP_BANNER'		  	=> 	new View('sources/site_top_banner'),
			'SITE_TOP_HORI_MENU' 		=> 	new View('sources/site_top_hori_menu', $this->data),
			'SITE_SEARCH_BOX' 			=> 	new View('sources/site_search_box'),
			'SITE_MIDDLE_CONTENT' 		=> 	new View($dynamicMiddleContent, $this->data),
			'SITE_TOP_LEFT_MENU' 		=> 	new View('sources/site_top_left_menu'),
			'SITE_MIDDLE_LEFT_MENU' 	=> 	new View($dynamicLeftMiddleContent, $this->data),
			'SITE_BOTTOM_LEFT_BOX' 		=> 	new View('sources/site_bottom_left_box'),
			'SITE_FOOTER_BLOCK' 		=> 	new View('sources/site_footer_block', $this->data)
		);
		
		$this->template->content = arr::to_object($tempContent);
	}
} // End Base Controller